---
#JUst some comment
dist: xenial # we need xenial to have mysql 5.7

language: generic

notifications:
  email: false

addons:
  postgresql: "9.6"

services:
  - mysql

env:
  global:
  - PGPASSWORD=elexisTest

before_install:
  - mysql --version
  - mysql -e 'SHOW VARIABLES LIKE "%case%";'
  - find . -name my.cnf
  - echo "[mysqld]" > $HOME/.my.cnf
  - echo "lower-case-table-names = 1" >> $HOME/.my.cnf
  - mysql --version
  - mysql -e 'SHOW VARIABLES LIKE "%case%";'
  - mysql -e 'SHOW VARIABLES LIKE "%version%";'
  - mysql -e 'CREATE DATABASE unittests;'
  - mysql -e "grant all on unittests.* to elexisTest@localhost identified by 'elexisTest';"
  - grep -w port /etc/postgresql/*/main/postgresql.conf
  - psql --version
  - psql -c "show server_version;"
  - psql -c "select version()";
  - psql -c "create user elexisTest with UNENCRYPTED password 'elexisTest';" -U postgres
  - psql -c "create database unittests;" -U postgres
  - psql --user=elexistest --host=localhost  unittests -f postgres.sql --echo-all

# Some Changes
