\set ON_ERROR_STOP true
select version();
show server_version;
\dt

drop table if exists role cascade;
drop table if exists USER_ cascade;
drop table if exists RIGHT_ cascade;
drop table if exists USER_ROLE_JOINT cascade;
drop table if exists ROLE_RIGHT_JOINT cascade;


CREATE TABLE USER_ ( ID VARCHAR(25) NOT NULL, DELETED CHAR(1) DEFAULT '0', KONTAKT_ID VARCHAR(25), LASTUPDATE BIGINT, HASHED_PASSWORD VARCHAR(64), SALT VARCHAR(64), IS_ACTIVE CHAR(1) DEFAULT '1', IS_ADMINISTRATOR CHAR(1) DEFAULT '0', KEYSTORE TEXT, EXTINFO BYTEA, PRIMARY KEY (ID) );
INSERT INTO USER_ (ID, IS_ADMINISTRATOR, SALT, HASHED_PASSWORD) VALUES ('Administrator', '1', '1254bb9a05856b9e', 'b94a0b6fc7be97e0a1585ac85e814d3852668968');
CREATE TABLE ROLE ( ID VARCHAR(25) NOT NULL, LASTUPDATE BIGINT DEFAULT NULL, DELETED CHAR(1) DEFAULT '0', EXTINFO BYTEA, ISSYSTEMROLE CHAR(1) DEFAULT '0', PRIMARY KEY (ID) );
INSERT INTO ROLE (ID, ISSYSTEMROLE) VALUES ('user', '1');
INSERT INTO ROLE (ID, ISSYSTEMROLE) VALUES ('user_external', '1');
INSERT INTO ROLE (ID, ISSYSTEMROLE) VALUES ('executive_doctor', '1');
INSERT INTO ROLE (ID, ISSYSTEMROLE) VALUES ('doctor', '1');
INSERT INTO ROLE (ID, ISSYSTEMROLE) VALUES ('assistant', '1');
INSERT INTO ROLE (ID, ISSYSTEMROLE) VALUES ('patient', '1');
CREATE TABLE USER_ROLE_JOINT ( ID VARCHAR(25) NOT NULL, LASTUPDATE BIGINT DEFAULT NULL, DELETED CHAR(1) DEFAULT NULL, USER_ID VARCHAR(25) NOT NULL, PRIMARY KEY (ID, USER_ID) );
CREATE TABLE RIGHT_ ( ID VARCHAR(25) NOT NULL, LASTUPDATE BIGINT DEFAULT NULL, DELETED CHAR(1) DEFAULT '0', LOG_EXECUTION CHAR(1), NAME VARCHAR(256), PARENTID VARCHAR(25), I18N_NAME VARCHAR(256), PRIMARY KEY (ID) );
INSERT INTO RIGHT_ (ID, NAME, PARENTID) VALUES ('root', 'root', '');
CREATE TABLE ROLE_RIGHT_JOINT ( ID VARCHAR(25) NOT NULL, LASTUPDATE BIGINT DEFAULT NULL, DELETED CHAR(1) DEFAULT NULL, ROLE_ID VARCHAR(25) NOT NULL, PRIMARY KEY (ID, ROLE_ID) );
CREATE OR REPLACE VIEW RIGHTS_PER_ROLE AS SELECT r.ID AS ROLE_ID, ri.ID AS RIGHT_ID FROM ROLE r LEFT JOIN ROLE_RIGHT_JOINT rrj ON r.ID = rrj.ROLE_ID LEFT JOIN RIGHT_ ri ON rrj.ID = ri.ID ORDER BY r.ID;
CREATE OR REPLACE VIEW RIGHTS_PER_USER AS SELECT u.ID AS USER_ID, ri.ID AS RIGHT_ID, ri.NAME AS RIGHT_NAME FROM USER_ u LEFT JOIN USER_ROLE_JOINT urj ON u.ID = urj.USER_ID LEFT JOIN ROLE r ON urj.ID = r.ID LEFT JOIN ROLE_RIGHT_JOINT rrj ON r.ID = rrj.ROLE_ID LEFT JOIN RIGHT_ ri ON rrj.ID = ri.ID ORDER BY u.ID;

\dt


--- next line produces problems
ALTER TABLE USER_ ADD COLUMN IF NOT EXISTS TOTP CHAR(16) NULL DEFAULT NULL ;
